### ISSUE TITLE
Java heap space exception in emdeppy

### ISSUE THREAD

**Issue by levaid** [dlt-rilmta/emtsv#10]
First of all, I don't know if the error is related to the apparent memory leaking of `emdep`, but when I start the process and it starts to analyze sentences, it takes up about 3-5 GBs of memory, and after some time, it jumps up by about 5-10 GBs of RAM usage, and stays high, peaking at about 25 GBs as I've seen.

But somewhere along the road, it throws a jnius.JavaException, and it stops. Below is the full traceback. I don't know whether the lack of memory or `no filename for stream` or some other thing is the cause here. After the traceback, I've put the code that is producing this error, although I've encountered while using emdep in every other way. 

Also, the corpus I'm using is filtered and was already fully analyzed by emmorph, and was reconstructed after the emMorph run, so it shouldn't contain anything that can cause a problem in emtsv. I am interested in hacky solution, basically anything that works. 

Maybe restarting the process every 500 sentences, or so? This exception is thrown after a few tens of thousands of sentences.

The exception is not thrown when opening a file, it is always while working on a file.

```
Traceback (most recent call last):
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/emdeppy/emdeppy/emdeppy.py", line 74, in process_sentence
    tok[field_names[3]]) for tok in sen)
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/emdeppy/emdeppy/emdeppy.py", line 107, in parse_sentence
    out = self._parser.apply(sentence_data)
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Java heap space

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/levai/anaconda3/envs/emtsv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/levai/anaconda3/envs/emtsv/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "dep_hesitating.py", line 26, in process_file
    outfile.writelines(build_pipeline(infile, used_tools, tools, presets, conll_comments))
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/xtsv/tsvhandler.py", line 61, in process
    for sen_count, (sen, comment) in enumerate(sentence_iterator(stream, conll_comments, track_stream)):
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/xtsv/tsvhandler.py", line 86, in sentence_iterator
    for line in input_stream:
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/xtsv/tsvhandler.py", line 71, in process
    with_traceback(sys.exc_info()[2])
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/emdeppy/emdeppy/emdeppy.py", line 74, in process_sentence
    tok[field_names[3]]) for tok in sen)
  File "/home/levai/Elmnyelv/harmony_nominals_thesis/corpora/cc_corp/emtsv/emdeppy/emdeppy/emdeppy.py", line 107, in parse_sentence
    out = self._parser.apply(sentence_data)
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: In "no filename for stream" at 4380: JVM exception occurred: Java heap space
```

So here is the example code, which really is copy&paste of the example code in python multiprocessing:

```
from emtsv import build_pipeline, jnius_config, tools, presets
import glob
import gzip
import time
import multiprocessing
import os

splitfiles = sorted(glob.glob('m_corp/split/*'))
jnius_config.classpath_show_warning = False  # To suppress warning


def process_file(inqueue):
    while not inqueue.empty():
        inputfname = inqueue.get()
        print(inputfname)
        outputfname = f"m_corp/dep/{inputfname.split('/')[-1].split('.')[0]}.tsv.gz"
        with open(inputfname) as infile, gzip.open(outputfname, 'wt') as outfile:
            used_tools = ['tok', 'spell', 'morph', 'pos', 'conv-morph', 'dep', 'chunk']
            conll_comments = True
            outfile.writelines(build_pipeline(infile, used_tools, tools, presets, conll_comments))
    else:
        print('worker done')
        return()


os.nice(1)
starttime = time.time()
filequeue = multiprocessing.Queue()
for file in splitfiles[5:]:
    filequeue.put(file)
number_of_processes = 2
reader_processes = []

for i in range(number_of_processes):
    reader_processes += [multiprocessing.Process(target=process_file, args=(filequeue,))]
for p in reader_processes:
    p.start()
for p in reader_processes:
    p.join()
```

**Comment by levaid** [comment]
Update:

I created a fresh, new conda environment and downloaded the emtsv repository again. This time, I called the emtsv from a bash script:
`python ~/Elmnyelv/old/emtsv/main.py tok,spell,morph,pos,conv-morph,dep,chunk -i $file -o $outfile`

And while running: 

Traceback (most recent call last):
  File "/home/levai/anaconda3/envs/emtsv_env/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/home/levai/Elmnyelv/old/emtsv/emdeppy/emdeppy/emdeppy.py", line 42, in process_sentence
    out = self._parse_sentence(((tok[field_names[0]], tok[field_names[1]], tok[field_names[2]],
  File "/home/levai/Elmnyelv/old/emtsv/emdeppy/emdeppy/emdeppy.py", line 81, in _parse_sentence_unlimited
    out = self._parser.apply(sentence_data)
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: Java heap space

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/home/levai/Elmnyelv/old/emtsv/main.py", line 24, in <module>
    output_iterator.writelines(build_pipeline(input_data, used_tools, tools, presets, conll_comments))
  File "/home/levai/anaconda3/envs/emtsv_env/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 61, in process
    for sen_count, (sen, comment) in enumerate(sentence_iterator(stream, conll_comments, track_stream)):
  File "/home/levai/anaconda3/envs/emtsv_env/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 86, in sentence_iterator
    for line in input_stream:
  File "/home/levai/anaconda3/envs/emtsv_env/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 70, in process
    raise type(e)('In "{0}" at {1}: {2}'.format(track_stream['file_name'], curr_line, str(e))).\
  File "/home/levai/anaconda3/envs/emtsv_env/lib/python3.8/site-packages/xtsv/tsvhandler.py", line 67, in process
    yield from ('{0}\n'.format('\t'.join(tok)) for tok in internal_app.process_sentence(sen, field_values))
  File "/home/levai/Elmnyelv/old/emtsv/emdeppy/emdeppy/emdeppy.py", line 42, in process_sentence
    out = self._parse_sentence(((tok[field_names[0]], tok[field_names[1]], tok[field_names[2]],
  File "/home/levai/Elmnyelv/old/emtsv/emdeppy/emdeppy/emdeppy.py", line 81, in _parse_sentence_unlimited
    out = self._parser.apply(sentence_data)
  File "jnius/jnius_export_class.pxi", line 766, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 843, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: In "no filename for stream" at 35562: JVM exception occurred: Java heap space

```

**Comment by dlazesz** [comment]
First of all, how long is your longest sentence? The memory usage (and speed) depends on the complexity of the sentences. You can skip parsing sentences which are longer than some specified length (in tokens). [See documentation](https://github.com/dlt-rilmta/emdeppy#usage) and [configuration example](https://github.com/dlt-rilmta/emtsv/blob/master/config.py#L63).

`no filename for stream` means that you supplied a stream instead of a file handle, so `In "no filename for stream" at 4380:` means it is the 4380th line of the input stream where the exception happens.

`JVM exception occurred: Java heap space` means Java has run out of memory.

I see that you are using two processes (`number_of_processes = 2`) and you are rebuilding the pipeline for every file (`outfile.writelines(build_pipeline(infile, used_tools, tools, presets, conll_comments))`) while doing a lot of stuff at once (`used_tools = ['tok', 'spell', 'morph', 'pos', 'conv-morph', 'dep', 'chunk']`).

1) How many RAM do you have for this operation?
2) Did you tried running all the tasks except the dependency parser in the first pass and do the parsing in a second pass?
3) Did you tried (2) but the second pass in one thread? (Because anna parser do internal multi-threading and therefore I do not expect it to be significantly faster running in multiple concurrent instances, however, it would eat memory up fast.) 
4) Another strategy is to chunk the stream and rebuild the pipeline after n sentences. Please consult [this SO thread](https://stackoverflow.com/questions/434287/what-is-the-most-pythonic-way-to-iterate-over-a-list-in-chunks) for chunked iterators. The rest should be trivial.

Sadly, we can not trace the error and fix it if it lies in PyJNIus or in anna parser, which is most likely the case.
Please report back with your findings, so we could update the documentation accordingly!

**Comment by levaid** [comment]
Thank you for your quick answer! 
As I was watching the sentences roll in, I have noticed that the dependency parsing is fast, but sometimes a sentence comes and it freezes for a while (meaning hours), so the problem should lay there. I am going to investigate in the following days, but I really hope it's just a monstrous sentence.

1. I have 150 GB free on the machine that I am running it.
2. I use 2 or maximum 3 concurrent processes because it uses up to 400% on the machine that I am using it. (which has 8 cores (16 threads) in 2 separate CPUs)
4. I was thinking about that too.

**Comment by levaid** [comment]
So, sentence length was the issue, the Java process throws an exception at around 25-30 GBs of RAM usage. 
The occurrence of these errors can be reduced by reducing the maximum length of the sentences. I had fairly good experience with a limit of 40, but this depends on the situation.

The issue can be closed, thank you for the heads up.

**Comment by dlazesz** [comment]
Thank you for reporting your findings!
